theme = "ia"

[editor]
gutters = []
color-modes = true
scroll-lines = 1
text-width = 72
popup-border = "all"
auto-completion = false
completion-timeout = 5

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.smart-tab]
enable = true

[editor.lsp]
auto-signature-help = false

[editor.whitespace.render]
# space = "all"
# tab = "all"

[editor.soft-wrap]
enable = false
wrap-indicator = ""

[editor.statusline]
left = [
    "file-name",
    "file-modification-indicator" 
]
right = [
    "diagnostics", 
    "register", 
    "position"
]

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.auto-pairs]
"«" = "»"
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
"'" = "'"
'`' = '`'

[keys.normal]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]
X = ["extend_line_above"]
V = ["extend_line_below", "select_mode"]
y = ["yank", ":clipboard-yank"]
d = ["delete_selection", ":clipboard-yank"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]

[keys.select]
"esc" = ["normal_mode", "collapse_selection"]
"{" = ["goto_prev_paragraph"]
"}" = ["goto_next_paragraph"]
