[[language]]
name = "javascript"
formatter = { command = "deno", args = ["fmt", "--indent-width", "4", "-"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "deno", args = ["fmt", "--indent-width", "4", "-"] }
auto-format = true

[[language]]
name = "html"
formatter = { command = "prettier", args = [
  "--parser", "html", "--tab-width", "4"
] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["ltex"]
scope = "text.markdown"

[[language]]
name = "css"
indent = { tab-width = 4, unit = "\t" }
formatter = { command = "prettier", args = ["--parser", "css"] }
auto-format = true

[[language]]
name = "git-commit"
rulers = []

[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["-"] }
auto-format = true

[[language]]
name = "go"
auto-format = true

[[language]]
name = "php"
auto-format = true

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
